export const jobListings = [
    {
      id: 1,
      title: 'Software Developer',
      location: 'New York, NY',
      salary: '$80,000 - $100,000',
      type: 'Full-time',
    },
    {
      id: 2,
      title: 'UX/UI Designer',
      location: 'San Francisco, CA',
      salary: '$70,000 - $90,000',
      type: 'Part-time',
    },
    {
      id: 3,
      title: 'Digital Marketing Specialist',
      location: 'Remote',
      salary: '$60,000 - $80,000',
      type: 'Freelancer',
    },
    {
      id: 4,
      title: 'Data Analyst',
      location: 'Chicago, IL',
      salary: '$75,000 - $95,000',
      type: 'Full-time',
    },
    {
      id: 5,
      title: 'Graphic Designer',
      location: 'Los Angeles, CA',
      salary: '$65,000 - $85,000',
      type: 'Part-time',
    },
    {
      id: 6,
      title: 'Content Writer',
      location: 'Remote',
      salary: '$50,000 - $70,000',
      type: 'Freelancer',
    },
    {
      id: 7,
      title: 'Front-end Developer',
      location: 'Seattle, WA',
      salary: '$85,000 - $105,000',
      type: 'Full-time',
    },
    {
      id: 8,
      title: 'Marketing Manager',
      location: 'Boston, MA',
      salary: '$90,000 - $110,000',
      type: 'Part-time',
    },
    {
      id: 9,
      title: 'SEO Specialist',
      location: 'Remote',
      salary: '$70,000 - $90,000',
      type: 'Freelancer',
    },
    {
      id: 10,
      title: 'Software Engineer',
      location: 'Austin, TX',
      salary: '$95,000 - $115,000',
      type: 'Full-time',
    },
    // Additional Full-time jobs
    {
      id: 11,
      title: 'Full-stack Developer',
      location: 'Denver, CO',
      salary: '$90,000 - $110,000',
      type: 'Full-time',
    },
    {
      id: 12,
      title: 'System Administrator',
      location: 'Atlanta, GA',
      salary: '$80,000 - $100,000',
      type: 'Full-time',
    },
    {
      id: 13,
      title: 'Mobile App Developer',
      location: 'Dallas, TX',
      salary: '$85,000 - $105,000',
      type: 'Full-time',
    },
    {
      id: 14,
      title: 'DevOps Engineer',
      location: 'Portland, OR',
      salary: '$95,000 - $115,000',
      type: 'Full-time',
    },
    {
      id: 15,
      title: 'Database Administrator',
      location: 'Miami, FL',
      salary: '$75,000 - $95,000',
      type: 'Full-time',
    },
    {
      id: 16,
      title: 'AI/ML Engineer',
      location: 'Phoenix, AZ',
      salary: '$100,000 - $120,000',
      type: 'Full-time',
    },
    {
      id: 17,
      title: 'Cybersecurity Analyst',
      location: 'Houston, TX',
      salary: '$90,000 - $110,000',
      type: 'Full-time',
    },
    {
      id: 18,
      title: 'Network Engineer',
      location: 'Raleigh, NC',
      salary: '$80,000 - $100,000',
      type: 'Full-time',
    },
    {
      id: 19,
      title: 'UI/UX Developer',
      location: 'Salt Lake City, UT',
      salary: '$85,000 - $105,000',
      type: 'Full-time',
    },
    {
      id: 20,
      title: 'Cloud Solutions Architect',
      location: 'Minneapolis, MN',
      salary: '$95,000 - $115,000',
      type: 'Full-time',
    },
    // Additional Part-time jobs
    {
      id: 21,
      title: 'Part-time Graphic Designer',
      location: 'Austin, TX',
      salary: '$30,000 - $40,000',
      type: 'Part-time',
    },
    {
      id: 22,
      title: 'Social Media Manager',
      location: 'Los Angeles, CA',
      salary: '$35,000 - $45,000',
      type: 'Part-time',
    },
    {
      id: 23,
      title: 'Part-time Writer',
      location: 'New York, NY',
      salary: '$25,000 - $35,000',
      type: 'Part-time',
    },
    {
      id: 24,
      title: 'Part-time Marketing Assistant',
      location: 'Chicago, IL',
      salary: '$28,000 - $38,000',
      type: 'Part-time',
    },
    {
      id: 25,
      title: 'Part-time Web Developer',
      location: 'San Francisco, CA',
      salary: '$40,000 - $50,000',
      type: 'Part-time',
    },
    {
      id: 26,
      title: 'Customer Support Representative',
      location: 'Seattle, WA',
      salary: '$32,000 - $42,000',
      type: 'Part-time',
    },
    {
      id: 27,
      title: 'Event Coordinator',
      location: 'Boston, MA',
      salary: '$38,000 - $48,000',
      type: 'Part-time',
    },
    {
      id: 28,
      title: 'Administrative Assistant',
      location: 'Denver, CO',
      salary: '$30,000 - $40,000',
      type: 'Part-time',
    },
    {
      id: 29,
      title: 'Sales Associate',
      location: 'Atlanta, GA',
      salary: '$35,000 - $45,000',
      type: 'Part-time',
    },
    {
      id: 30,
      title: 'Part-time Software Tester',
      location: 'Dallas, TX',
      salary: '$42,000 - $52,000',
      type: 'Part-time',
    },
    // Additional Freelancer jobs
    {
      id: 31,
      title: 'Freelance Graphic Designer',
      location: 'Remote',
      salary: '$50 - $70 per hour',
      type: 'Freelancer',
    },
    {
      id: 32,
      title: 'Freelance Copywriter',
      location: 'Remote',
      salary: '$40 - $60 per hour',
      type: 'Freelancer',
    },
    {
      id: 33,
      title: 'Freelance Photographer',
      location: 'Remote',
      salary: '$60 - $80 per hour',
      type: 'Freelancer',
    },
    {
      id: 34,
      title: 'Freelance Web Developer',
      location: 'Remote',
      salary: '$70 - $90 per hour',
      type: 'Freelancer',
    },
    {
      id: 35,
      title: 'Freelance Marketing Consultant',
      location: 'Remote',
      salary: '$80 - $100 per hour',
      type: 'Freelancer',
    },
    {
      id: 36,
      title: 'Freelance Social Media Manager',
      location: 'Remote',
      salary: '$45 - $65 per hour',
      type: 'Freelancer',
    },
    {
      id: 37,
      title: 'Freelance UX Designer',
      location: 'Remote',
      salary: '$55 - $75 per hour',
      type: 'Freelancer',
    },
    {
      id: 38,
      title: 'Freelance Software Developer',
      location: 'Remote',
      salary: '$75 - $95 per hour',
      type: 'Freelancer',
    },
    {
      id: 39,
      title: 'Freelance Content Writer',
      location: 'Remote',
      salary: '$35 - $55 per hour',
      type: 'Freelancer',
    },
    {
      id: 40,
      title: 'Freelance SEO Specialist',
      location: 'Remote',
      salary: '$65 - $85 per hour',
      type: 'Freelancer',
    },
  ];